import { test, expect } from '@playwright/test'

test('consolida todos os projetos por destino e registra uma NF para a remessa', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('tab', { name: 'Consolidado por localidade' }).click()
  const location = page.locator('details.location-group').filter({ has: page.getByRole('heading', { name: 'EQUINIX SP4', exact: true }) })
  await expect(location.getByText('PSC 2103', { exact:true })).toHaveCount(2)
  await expect(location.getByText('PS 2180', { exact:true })).toBeVisible()
  await page.getByLabel('Selecionar PSC 2103 Transceiver QSFP56 DR4+ MPO', { exact:true }).check()
  await page.getByLabel('Selecionar PS 2180 Transceiver SFP+ 10G LR', { exact:true }).check()
  await expect(page.getByLabel('Selecionar PS 2180 Cordão óptico LC/UPC – LC/UPC', { exact:true })).toBeDisabled()
  await page.getByRole('button', { name: 'Criar remessa', exact:true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Quantidade de PSC 2103 Transceiver QSFP56 DR4+ MPO').fill('2')
  await dialog.getByRole('button', {name:'Criar remessa', exact:true}).click()
  await expect(page.getByRole('heading', {name:'Remessas e notas fiscais'})).toBeVisible()
  await expect(page.getByRole('button', {name:'Registrar solicitação de NF', exact:true})).toHaveCount(0)
  await page.getByRole('button', {name:'Informar número da NF'}).click()
  await page.getByLabel('Número da NF', {exact:true}).fill('000987')
  await page.getByRole('button', {name:'Salvar registro'}).click()
  await page.getByRole('button', {name:'Entregar à logística', exact:true}).click()
  await page.getByRole('button', {name:'Salvar registro'}).click()
  await expect(page.locator('.shipment-status').filter({hasText:'Entregue à logística'}).first()).toBeVisible()
  await expect(page.getByText('000987', {exact:true})).toBeVisible()
})

test('filtra localidades, edita materiais e exporta somente a visualização', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('tab', {name:'Consolidado por localidade'}).click()
  await page.getByLabel('Localidade', {exact:true}).selectOption({label:'BANDEIRANTES'})
  await expect(page.locator('details.location-group')).toHaveCount(1)
  await page.getByLabel('Situação de PSC 2103 Distribuidor óptico 24 posições', {exact:true}).selectOption('separado')
  await expect(page.getByLabel('Situação de PSC 2103 Distribuidor óptico 24 posições', {exact:true})).toBeEnabled()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByLabel('Situação de PSC 2103 Distribuidor óptico 24 posições', {exact:true})).toHaveValue('separado')
  await page.reload()
  await page.getByRole('tab', {name:'Consolidado por localidade'}).click()
  await page.getByLabel('Localidade', {exact:true}).selectOption({label:'BANDEIRANTES'})
  await expect(page.getByLabel('Situação de PSC 2103 Distribuidor óptico 24 posições', {exact:true})).toHaveValue('separado')
  const download = page.waitForEvent('download')
  await page.getByRole('button', {name:'Exportar seleção de filtros'}).click()
  const result = await download
  const stream = await result.createReadStream()
  let content = ''; for await (const part of stream!) content += part.toString()
  expect(content).toContain('BANDEIRANTES')
  expect(content).not.toContain('EQUINIX SP4')
})

test('cadastro manual e adição de material persistem após recarregar', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('navigation').getByRole('button', {name:'Projetos'}).click()
  await page.getByRole('button', {name:'Novo projeto'}).click()
  await page.getByLabel('PS / PSC', {exact:true}).fill('PSC 9999')
  await page.getByRole('button', {name:'Adicionar linha'}).click()
  await page.getByLabel('Localidade da linha 1').fill('SITE TESTE')
  await page.getByLabel('Material da linha 1').fill('Material de teste')
  await page.getByRole('button', {name:'Confirmar projeto com 1 materiais'}).click()
  await expect(page.getByRole('heading', {name:'PSC 9999', exact:true})).toBeVisible()
  await page.reload()
  await page.getByRole('tab', {name:'Consolidado por localidade'}).click()
  await expect(page.getByRole('heading', {name:'SITE TESTE', exact:true})).toBeVisible()
})

test('mobile e falha de conexão têm estados utilizáveis', async ({ page }) => {
  await page.setViewportSize({width:390,height:844})
  await page.goto('/')
  await page.getByRole('tab', {name:'Consolidado por localidade'}).click()
  await expect(page.getByRole('heading', {name:'Todos os projetos. Um destino por vez.'})).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', {name:'Abrir menu'}).click()
  await page.getByRole('navigation').getByRole('button', {name:'Projetos'}).click()
  await expect(page.getByRole('heading', {name:'Projetos', exact:true})).toBeVisible()
  await page.route('**/api/**', route => route.abort())
  await page.getByRole('button', {name:'Atualizar dados'}).click()
  await expect(page.getByRole('alert')).toContainText('Não foi possível conectar')
})
