import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowUpRight, FileText, LoaderCircle, Pencil, Plus, Search, Trash2, Upload } from 'lucide-react'
import { api, request } from '../api'
import { emptyItem, type DraftItem, type Extraction, type Project } from '../types'
import { AsyncForm, Empty, ErrorBox, Modal } from '../components/UI'
export function Projects({ projects, reload, notify, openProject }: { projects: Project[]; reload: () => Promise<void>; notify: (s: string) => void; openProject: (id: string) => void }) {
  const [create, setCreate] = useState(false), [editing, setEditing] = useState<Project | null>(null), [search, setSearch] = useState('')
  const filtered = useMemo(() => {
    const term = search.trim().toLowerCase()
    return projects.filter(p => `${p.codigo} ${p.arquivo} ${p.responsavel_implantacao}`.toLowerCase().includes(term))
  }, [projects, search])
  return <><div className="page-heading"><div><div className="eyebrow">PROJETOS • PS / PSC</div><h1>Projetos</h1><p>Importe a lista de materiais e acompanhe os projetos de implantação.</p></div><button className="button primary" onClick={() => setCreate(true)}><Plus size={17}/>Novo projeto</button></div>
    <div className="project-toolbar"><div className="input-icon"><Search size={18}/><input aria-label="Buscar projetos" placeholder="Buscar PS/PSC, arquivo ou responsável…" value={search} onChange={e => setSearch(e.target.value)}/></div><span>{filtered.length} projetos</span></div>
    {!filtered.length ? <section className="panel"><Empty title="Nenhum projeto encontrado">Use Novo projeto para importar um documento ou cadastrar os materiais.</Empty></section> : <div className="project-grid">{filtered.map(p => { const separated = p.itens.filter(i => i.status === 'separado').length; return <article className="project-card" key={p.id}><div className="project-card-top"><span className="file-icon"><FileText size={22}/></span><button className="icon-button" aria-label={`Editar responsáveis de ${p.codigo}`} onClick={() => setEditing(p)}><Pencil size={16}/></button></div><h2>{p.codigo}</h2><p className="file-name" title={p.arquivo}>{p.arquivo || 'Cadastro manual'}</p><div className="project-facts"><span><strong>{p.itens.length}</strong> materiais</span><span><strong>{new Set(p.itens.map(i => i.localidade_id).filter(Boolean)).size}</strong> localidades</span></div><div className="progress-label"><span>Separação</span><strong>{separated}/{p.itens.length}</strong></div><progress value={separated} max={p.itens.length || 1}/><div className="person"><span>Responsável pela implantação</span><strong>{p.responsavel_implantacao || 'Não informado'}</strong></div><button className="card-link" onClick={() => openProject(p.id)}>Separar materiais<ArrowUpRight size={18}/></button></article> })}</div>}
    {create && <ProjectCreator onClose={() => setCreate(false)} onSaved={async () => { await reload(); notify('Projeto salvo. Materiais disponíveis na Separação.'); setCreate(false) }}/>}
    {editing && <PeopleEditor project={editing} onClose={() => setEditing(null)} onSaved={async () => { await reload(); notify('Responsáveis atualizados.'); setEditing(null) }}/>}
  </>
}
function PeopleEditor({ project, onClose, onSaved }: {project: Project; onClose: () => void; onSaved: () => Promise<void>}) {
  const [author, setAuthor] = useState(project.projetista), [owner, setOwner] = useState(project.responsavel_implantacao)
  return <Modal title={`Responsáveis • ${project.codigo}`} onClose={onClose}><AsyncForm label="Salvar responsáveis" onCancel={onClose} onSubmit={async () => { await request(`/projetos/${project.id}`, 'PATCH', { projetista: author, responsavel_implantacao: owner }); await onSaved() }}><label>Projetista<input value={author} onChange={e => setAuthor(e.target.value)}/></label><label>Responsável pela implantação<input value={owner} onChange={e => setOwner(e.target.value)}/></label></AsyncForm></Modal>
}
function ProjectCreator({ onClose, onSaved }: { onClose: () => void; onSaved: () => Promise<void> }) {
  const [file, setFile] = useState<File | null>(null), [preview, setPreview] = useState(''), [result, setResult] = useState<Extraction | null>(null)
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [code, setCode] = useState(''), [author, setAuthor] = useState(''), [owner, setOwner] = useState('')
  const [rows, setRows] = useState<DraftItem[]>([])
  const fileInput = useRef<HTMLInputElement>(null)
  useEffect(() => { if (!file || !file.name.toLowerCase().endsWith('.pdf')) { setPreview(''); return }; const url = URL.createObjectURL(file); setPreview(url); return () => URL.revokeObjectURL(url) }, [file])
  async function extract(f: File) { if (f.size > 30 * 1024 * 1024) { setError('O arquivo deve ter no máximo 30 MB.'); return }; setBusy(true); setError(''); setFile(f); setResult(null); setRows([]); try { const r = await api.extract(f); setResult(r); setCode(r.codigo); setRows(r.itens) } catch (e) { setError(e instanceof Error ? e.message : 'Falha na leitura.') } finally { setBusy(false) } }
  function edit(index: number, key: keyof DraftItem, value: string | number | null) { setRows(v => v.map((r, i) => i === index ? { ...r, [key]: value } : r)) }
  return <Modal title="Novo projeto" subtitle="Importe, confira os materiais e confirme o cadastro." onClose={onClose} busy={busy} wide>
    <button type="button" className="upload-area" disabled={busy} aria-label="Importar lista de materiais" onClick={() => fileInput.current?.click()}><Upload size={26}/><span><strong>{busy ? 'Lendo o documento…' : 'Importar lista de materiais'}</strong><span className="upload-help">PDF, DOCX ou DOC · até 30 MB</span></span><span className="button secondary upload-label">{busy ? <LoaderCircle size={17} className="spin"/> : <FileText size={17}/>}Escolher arquivo</span></button>
    <input ref={fileInput} hidden aria-label="Importar documento" type="file" accept=".pdf,.docx,.doc" disabled={busy} onChange={e => { const f = e.target.files?.[0]; e.target.value = ''; if (f) void extract(f) }}/>
    <ErrorBox message={error}/>{result?.aviso && <p className="notice">{result.aviso}</p>}
    <AsyncForm label={rows.length ? `Confirmar projeto com ${rows.length} materiais` : 'Criar projeto vazio'} onCancel={onClose} onSubmit={async () => { if (busy) throw new Error('Aguarde a leitura do documento.'); if (file && !result) throw new Error('A leitura falhou. Escolha outro arquivo ou feche e crie um cadastro manual.'); if (rows.some(r => !r.destino.trim() || !r.descricao.trim() || !Number.isInteger(r.quantidade) || (r.quantidade ?? 0) <= 0)) throw new Error('Confira destino, material e quantidade de todas as linhas.'); await request('/projetos', 'POST', { codigo: code, projetista: author, responsavel_implantacao: owner, arquivo: result?.arquivo ?? '', paginas: result?.paginas ?? 0, metodo: result?.metodo ?? 'manual', itens: rows.map(({ revisao: _review, ...r }) => r) }); await onSaved() }}>
      <div className="form-grid thirds"><label>PS / PSC<input required placeholder="PSC 2103" value={code} onChange={e => setCode(e.target.value)}/></label><label>Projetista<input value={author} onChange={e => setAuthor(e.target.value)}/></label><label>Responsável pela implantação<input value={owner} onChange={e => setOwner(e.target.value)}/></label></div>
      {preview && <details className="document-preview"><summary>Visualizar documento original</summary><object data={preview} type="application/pdf" aria-label="Documento original"><a href={preview} target="_blank" rel="noreferrer">Abrir documento original</a></object></details>}
      {result?.imagem_png && <details className="document-preview"><summary>Visualizar recorte reconhecido</summary><img alt="Região da tabela reconhecida por OCR" src={`data:image/png;base64,${result.imagem_png}`}/></details>}
      <div className="subheading"><h3>Conferência de materiais <span className="count">{rows.length}</span></h3><button className="button secondary small" type="button" disabled={busy} onClick={() => setRows(v => [...v, emptyItem()])}><Plus size={15}/>Adicionar linha</button></div>
      {!!rows.length && <div className="table-scroll draft-table"><table><thead><tr><th>Localidade</th><th>Material</th><th>Quantidade</th><th>Conferência</th><th/></tr></thead><tbody>{rows.map((r, i) => <tr key={i}><td><input required aria-label={`Localidade da linha ${i + 1}`} value={r.destino} onChange={e => edit(i, 'destino', e.target.value)}/></td><td><input required aria-label={`Material da linha ${i + 1}`} value={r.descricao} onChange={e => edit(i, 'descricao', e.target.value)}/></td><td><input required aria-label={`Quantidade da linha ${i + 1}`} className="quantity-input" type="number" min="1" step="1" value={r.quantidade ?? ''} onChange={e => edit(i, 'quantidade', e.target.value === '' ? null : Number(e.target.value))}/></td><td><small className="review-text">{r.revisao || 'Conferir com o original'}</small></td><td><button className="icon-button" type="button" aria-label={`Remover linha ${i + 1}`} onClick={() => setRows(v => v.filter((_, n) => n !== i))}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div>}
      {!rows.length && <p className="muted">Você também pode criar o projeto e adicionar os materiais depois, na tela de Separação.</p>}
    </AsyncForm>
  </Modal>
}
